version: '3.9'

services:
  redis:
    restart: "no"
    image: "redis:alpine"
    hostname: redis
    container_name: redis
    ports:
      - '6379:6379'


  backend:
    restart: "no"
    build:
      context: ./django-backend
      dockerfile: Dockerfile
    command: sh -c "gunicorn FinalProject.wsgi --bind 0.0.0.0:8000 -w 4"
    container_name: backend
    image: backend_image
    volumes:
      - ./django-backend:/backend
    ports:
      - '8000:8000'
    links:
      - redis
    depends_on:
      - redis

  celery:
    build:
      context: ./django-backend
      dockerfile: Dockerfile
    command: celery -A FinalProject worker -l INFO
    container_name: celery
    volumes:
      - ./django-backend:/backend
    environment:
      - DEBUG=1
      - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

  frontend:
    restart: "no"
    build:
      context: ./vue-frontend
      dockerfile: Dockerfile
    container_name: frontend
    image: frontend_image
    depends_on:
      - backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./django-backend/static:/backend/static
      - ./django-backend/media:/backend/media
    ports:
      - "80:80"
